### ISSUE TITLE
Colaboración escasa.

### ISSUE THREAD

**Issue by lauramcastro** [adrianudc/vvs-practica3#2]
Un dos membros do equipo só incluiu o README no repositorio. Debedes mellorar o ratio de colaboración.

**Comment by adrianudc** [comment]
Hola Laura, los colaboradores del repositorio han hecho commits de las tareas asignadas. No es correcto que un miembro sólamente haya subido el archivo README.

**Comment by lauramcastro** [comment]
La mayoría de los commits de @adrianudc no estaban siendo correctamente asignados a él como colaborador. A juzgar por el último commit (que sí se atribuye) entiendo que habéis detectado por qué y lo habéis solucionado.

**Comment by adrianudc** [comment]
El problema es la configuración del git de la máquina, al usarla para trabajar se estaban asignando a otro colaborador y no me di cuenta.

El último commit está correcto porque modifiqué el README dentro de github.

**Comment by lauramcastro** [comment]
Bien, asegúrate de que a partir de ahora la configuración es correcta cuando hagas commit a este repositorio.

**Comment by lauramcastro** [comment]
Este problema non foi arreglado: os commits de @adrianudc seguen sen atribuírselle correctamente.

**Comment by adrianudc** [comment]
No hubo commits nuevos con ese usuario. 

En un mensaje anterior indicaste:

_Bien, asegúrate de que a partir de ahora la configuración es correcta cuando hagas commit a este repositorio._

Quieres que cambie los commits subidos?

**Comment by lauramcastro** [comment]
Cierto, me despisté con las fechas, perdón. Creo que retroactivamente no pueden cambiarse, así que no te preocupes por los commits pasados.

**Comment by adrianudc** [comment]
Sí, el problema es que desde los commit iniciales hubo este problema y no me di cuenta. 

Ya está corregido, si hubiese que hacer un nuevo commit ya estaría bien.

La solución sería hacer rebases sobre la rama master...
