### ISSUE TITLE
Especificación del método buscar de la interfaz Contenido.

### ISSUE THREAD

**Issue by martinquinteiro** [adrianudc/vvs-practica3#4]
La especificación del método buscar de la interfaz Contenido "List<Contenido> buscar(String cadena)" no corresponde con la especificación original del Moodle (tomada como referencia al no existir todavía documentación propia de vuestro proyecto) , que aplicada al lenguaje de programación Java sería "List<Contenido> buscar(String subcadena)".

**Comment by ymishchenko** [comment]
Corregido.
