### ISSUE TITLE
Fallos en los tests

### ISSUE THREAD

**Issue by cristiancanosa** [adrianudc/vvs-practica3#5]
Resumen:
Se han ejecutado varias veces los tests con el resultado fallido en varios de ellos, como se aprecia en la imagen adjunta.
![issuefallostest](https://cloud.githubusercontent.com/assets/15655226/11097695/02d972f0-88a1-11e5-97c4-e1621e9eda1b.png)
Despúes de varios intentos fallidos, los tests se ejecutaban correctamente sin fallos.

**Comment by adrianudc** [comment]
Hola cristian.

No he podido reproducir el error en las dos máquinas que he podido probar. ¿Es posible que tengas el puerto ocupado?

Por favor, ejecuta tests fallidos con --stacktrace para comprobar en los logs si ese es el error. La imagen no aporta mucho más información que el NullpointerException.

**Comment by cristiancanosa** [comment]
Debio ser un fallo del equipo que hemos utilizado en ese momento para ejecutar los tests. Ahora ya no da ningún fallo similar y pasan todas las pruebas.

**Comment by adrianudc** [comment]
Ok, cierro el issue.
