### ISSUE TITLE
Error en la especificación de la interfaz servidor

### ISSUE THREAD

**Issue by fran464646** [adrianudc/vvs-practica3#7]
Según la especificación de la práctica, la interfaz servidor no debe extender a ninguna otra interfaz.

**Comment by adrianudc** [comment]
Hola Fran, ¿podrías aclararme donde viene tal especificación?

**Comment by fran464646** [comment]
En el moodle. En la explicación de esta práctica.

**Comment by adrianudc** [comment]
Perdona Fran, pero no veo tal explicación en ningún sitio. ¿Puedes aclararme **explícitamente** donde viene tal especificación?

**Comment by lauramcastro** [comment]
@fran464646 se refiere al enunciado: https://moodle.udc.es/mod/page/view.php?id=343367

Ciertamente, no hay ninguna razón para que Servidor tenga que ser una especialización de TokenServidor en lugar de al revés, y desde el punto de vista del diseño estáis añadiendo responsabilidades/métodos al API de Servidor que se exige en el enunciado. Recomiendo el rediseño intercambiando los roles de las mencionadas interfaces.

**Comment by fran464646** [comment]
:+1:

**Comment by adrianudc** [comment]
fixed
